### ISSUE TITLE
Which Java compiler version?

### ISSUE THREAD

**Issue by desruisseaux** [Unidata/geoapi-netcdf-java#3]
The code should be executable on Java 8. But should it be compiled with Java 8 as well, or do we use Java 11 with `--release 8` option? The `--release` option is available since Java 9 and replaces the combination of `-source`, `-target` and `-bootclasspath` options that we were used to do for cross-version compilation. I guess that we should apply the same policy than the rest of UCAR library, but what is this policy?

**Comment by lesserwhirls** [comment]
Currently, we set both `-source` and `-target` to `1.8`. We plan on moving both to Java 11 in version 7 of the library (will be starting that work in the next month or so).

**Comment by lesserwhirls** [comment]
Ah, forgot to add that we use Java 8 when creating our artifacts.

**Comment by desruisseaux** [comment]
Okay, thanks. I will modify the root `pom.xml` for compatibility with the `javac` compiler of JDK 8 (as opposed to compiling with JDK 15 with `--release 8` option enabled).

**Comment by lesserwhirls** [comment]
Sounds good - thank you @desruisseaux!
